CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(50)                             NOT NULL,
    name  VARCHAR(50)                             NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,

    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uc_categories_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         VARCHAR(2000)                           NOT NULL,
    category_id        BIGINT                                  NOT NULL,
    description        VARCHAR(7000)                           NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    paid               BOOLEAN                                 NOT NULL,
    participant_limit  INTEGER                                 NOT NULL,
    confirmed_requests INTEGER                                 NOT NULL,
    request_moderation BOOLEAN                                 NOT NULL,
    title              VARCHAR(120)                            NOT NULL,
    location_latitude  FLOAT                                   NOT NULL,
    location_longitude FLOAT                                   NOT NULL,
    state              VARCHAR(10)                             NOT NULL,
    initiator_id       BIGINT                                  NOT NULL,
    date_created       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,

    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT uc_events_annotation UNIQUE (annotation),
    CONSTRAINT FK_EVENTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE,
    CONSTRAINT FK_EVENTS_ON_INITIATOR FOREIGN KEY (initiator_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS participation_requests
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requester_id   BIGINT                                  NOT NULL,
    event_id       BIGINT                                  NOT NULL,
    date_created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    request_status VARCHAR(10)                             NOT NULL,

    CONSTRAINT pk_participation_requests PRIMARY KEY (id),
    CONSTRAINT uc_participation_requests_requester_event UNIQUE (requester_id, event_id),
    CONSTRAINT FK_PARTICIPATION_REQUESTS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT FK_PARTICIPATION_REQUESTS_ON_REQUESTER FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE
);