version: '3.1'
services:
  stats-server:
    build: stats-service/server
    image: stats-service-image
    container_name: stats-service-container
    ports:
      - "9090:9123"
    depends_on:
      - stats-db
    environment:
      - SERVER_PORT=9123
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats
      - SPRING_DATASOURCE_USERNAME=DB_stats_admin
      - SPRING_DATASOURCE_PASSWORD=sdf51sfs15sf999r

  stats-db:
    image: postgres:15.2-alpine
    container_name: stats-postgres-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_stats
      - POSTGRES_USER=DB_stats_admin
      - POSTGRES_PASSWORD=sdf51sfs15sf999r

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:15.2-alpine
