CREATE TABLE IF NOT EXISTS apps
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,

    CONSTRAINT pk_apps PRIMARY KEY (id),
    CONSTRAINT uc_apps_name UNIQUE (name)
);


CREATE TABLE IF NOT EXISTS endpoint_hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_id    BIGINT                                  NOT NULL,
    uri       VARCHAR(1000)                           NOT NULL,
    ip        VARCHAR(15)                             NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,

    CONSTRAINT pk_endpoint_hits PRIMARY KEY (id),
    CONSTRAINT FK_ENDPOINT_HITS_ON_APP FOREIGN KEY (app_id) REFERENCES apps (id) ON DELETE CASCADE
);

